version: '3'
services:
  app:
    container_name: tolgee_e2e
    image: tolgee/tolgee:local
    ports:
      - 8201:8080
      - 8091:8091
    environment:
      - tolgee.internal.populate=true
      - tolgee.internal.controllerEnabled=true
      - "tolgee.screenshots-url=http://localhost:8201/screenshots"
      - tolgee.authentication.needs-email-verification=true
      - tolgee.authentication.registrations-allowed=true
      - tolgee.internal.fake-emails-sent=true
      - tolgee.authentication.initialPassword=admin
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:8091,server=y,suspend=n