name: Test

on:
  push:
    branches-ignore:
      "main"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run E2E test
        run: ./gradlew runE2e

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test
          path: |
            ./e2e/cypress/videos/**/*
            ./e2e/screenshots/**/*
            ./build/reports/**/*